### ISSUE TITLE
pong2_launcher.py type error

### ISSUE THREAD

**Issue by samuelhorobin** [nsetzer/mpgameserver#11]
pygame-ce 2.4.0 (SDL 2.28.5, Python 3.12.3)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\misc\Projects\mpgameserver\demo\pong2_client.py", line 14, in <module>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\misc\Projects\mpgameserver\demo\pong2_client.py", line 14, in <module>
    from mpgameserver import Timer, RetryMode, Serializable
  File "D:\misc\Projects\mpgameserver\mpgameserver\__init__.py", line 4, in <module>
    from mpgameserver import Timer, RetryMode, Serializable
    from mpgameserver.auth import Auth
  File "D:\misc\Projects\mpgameserver\mpgameserver\__init__.py", line 4, in <module>
  File "D:\misc\Projects\mpgameserver\mpgameserver\auth.py", line 6, in <module>
    from cryptography.hazmat.primitives.kdf import scrypt
    from mpgameserver.auth import Auth
  File "D:\misc\Projects\mpgameserver\mpgameserver\auth.py", line 6, in <module>
ModuleNotFoundError: No module named 'cryptography'
    from cryptography.hazmat.primitives.kdf import scrypt
ModuleNotFoundError: No module named 'cryptography'
10.23229718208313
Traceback (most recent call last):
  File "d:\misc\Projects\mpgameserver\demo\pong2_launcher.py", line 96, in <module>
    for idx, (hwnd, cpid, rect) in enumerate(hwnds):
             ^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Came across this when trying to run pong2_launcher.py!

**Comment by nsetzer** [comment]
I added some error handling to the launcher script. It is windows only. I also see a error where cryptography is not installed, so perhaps there was an issue with the virtual environment?

**Comment by St-ZFeng** [comment]
```
No module named demo.pong2_client
No module named demo.pong2_client
```

I think this is the reason

**Comment by St-ZFeng** [comment]
I can't use `python -m demo.pong2_client` in cmd. Is there a component I'm missing?
